services:
  ### БАЗА ДАННЫХ PostgreSQL
  postgres:
    image: postgres:15
    container_name: zabbix-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - zabbix-db:/var/lib/postgresql/data
    networks:
      - zabbix-net

  ### СЕРВЕР ZABBIX
  zabbix-server:
    image: zabbix/zabbix-server-pgsql:trunk-ubuntu
    container_name: zabbix-server
    restart: unless-stopped
    environment:
      DB_SERVER_HOST: ${DB_SERVER_HOST}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    depends_on:
      - postgres
    ports:
      - "10051:10051"
    networks:
      - zabbix-net

  ### ВЕБ-ИНТЕРФЕЙС ZABBIX
  zabbix-web:
    image: zabbix/zabbix-web-nginx-pgsql:trunk-ubuntu
    container_name: zabbix-web
    restart: unless-stopped
    environment:
      ZBX_SERVER_HOST: ${ZBX_SERVER_HOST}
      DB_SERVER_HOST: ${DB_SERVER_HOST}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    depends_on:
      - zabbix-server
    ports:
      - "8080:8080"
    networks:
      - zabbix-net

  ### АГЕНТ ZABBIX (для мониторинга самого сервера)
  zabbix-agent:
    image: zabbix/zabbix-agent:trunk-ubuntu
    container_name: zabbix-agent
    restart: unless-stopped
    environment:
      ZBX_SERVER_HOST: ${ZBX_SERVER_HOST}
    depends_on:
      - zabbix-server
    networks:
      - zabbix-net

networks:
  zabbix-net:

volumes:
  zabbix-db:
