services:
  influxdb-grafana:
    image: playniuniu/influxdb-grafana-demo:latest
    container_name: influxdb_grafana
    restart: unless-stopped
    ports:
      - "3020:3020"  # Grafana UI
      - "8086:8086"  # InfluxDB API
    environment:
      - INFLUXDB_ADMIN_USER=${INFLUXDB_USER}
      - INFLUXDB_ADMIN_PASSWORD=${INFLUXDB_PASSWORD}
      - GRAFANA_ADMIN_USER=${GRAFANA_USER}
      - GRAFANA_ADMIN_PASSWORD=${GRAFANA_PASSWORD}
    volumes:
      - ./data:/var/lib/influxdb
      - ./config:/etc/grafana
