services:
  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000" # API MinIO (S3 совместимый)
      - "9001:9001" # Веб-консоль MinIO
    environment:
      - MINIO_ROOT_USER=admin # Логин
      - MINIO_ROOT_PASSWORD=adminpassword # Пароль
    volumes:
      - "./data:/data" # Хранение данных локально
    command: server /data --console-address ":9001"
